import type {InternalSession} from "#~src/internal/InternalSession.d.mts"
import {scandir, remove} from "@anio-software/pkg.node-fs"
import {isAutogeneratedFile} from "#~src/internal/autogenerate/isAutogeneratedFile.mts"
import path from "node:path"

export async function removeObsoleteAutogeneratedFiles(
	session: InternalSession
) {
	const projectFiles = await scandir(
		path.join(session.projectRoot, "project"), {
			filter(entry) {
				return entry.type === "file:regular"
			}
		}
	)

	for (const projectFile of projectFiles) {
		const absolutePath = projectFile.absolutePath
		const relativePath = projectFile.relativePath

		const isAutogenerated = await isAutogeneratedFile(absolutePath)

		if (!isAutogenerated) continue
		if (session.state.filesToAutogenerate.has(relativePath)) continue

		session.emitMessage(
			"debug",
			`removing obsolete autogenerated file '${projectFile.relativePath}'`
		)

		await remove(absolutePath)
	}
}
