import {defineConfig, defineAutogeneratedFile} from "@anio-software/enkore"
import {defineTargetOptions} from "@anio-software/enkore.target-js-node"
import {buildStepsTypeFile} from "./config/enkore/buildStepsTypeFile.mts"
import {buildRunAllStepsFile} from "./config/enkore/buildRunAllStepsFile.mts"

export const config: unknown = defineConfig({
	target: {
		name: "js-node",
		options: defineTargetOptions({
			registry: {
				"anioSoftware": {
					url: "https://npm-registry.anio.software",
					authTokenFilePath: "secrets/anio_npm_auth_token",
					clientPrivateKeyFilePath: "secrets/npm_client.pkey",
					clientCertificateFilePath: "secrets/npm_client.cert"
				}
			},

			packageSourceRegistryByScope: {
				"@anio-software": {
					registry: "anioSoftware"
				}
			},

			exports: {
				"default": {
					checkAgainstInterface: [
						"@anio-software/enkore-private.spec",
						"EnkoreNodeAPI_V0_Rev0"
					]
				}
			},

			publish: [{
				registry: "anioSoftware"
			}]
		})
	},

	autogeneratedFiles: [
		defineAutogeneratedFile({
			destinationPath: "project/src/Steps.ts",
			generator() {
				return buildStepsTypeFile()
			}
		}),
		defineAutogeneratedFile({
			destinationPath: "project/src/runAllSteps.ts",
			generator() {
				return buildRunAllStepsFile()
			}
		})
	]
})
