import type {InternalSession} from "../InternalSession.d.mts"
import {scandir, readFileInChunks, remove} from "@aniojs/node-fs"
import path from "node:path"
import {autoGeneratedFileMarkerUUID} from "@enkore/spec/uuid"

export async function removeObsoleteAutoGeneratedFiles(
	session: InternalSession
) {
	const projectFiles = await scandir(
		path.join(session.projectRoot, "project"), {
			filter(entry) {
				return entry.type === "regularFile"
			}
		}
	)

	for (const projectFile of projectFiles) {
		const absolutePath = projectFile.absolute_path
		const relativePath = projectFile.relative_path

		const tmp = await readFileInChunks(absolutePath, 512)
		const chunk = await tmp.readNextChunk()

		if (chunk === false) continue

		const firstChunkString = chunk.toString()

		if (!firstChunkString.includes(autoGeneratedFileMarkerUUID)) continue

		if (session.filesToAutoGenerate.has(relativePath)) continue

		await remove(absolutePath)
	}
}
