import {
	createEntity,
	type EnkoreAutogeneratedFile,
	type EnkoreSessionAPI
} from "@enkore/spec"

export function defineAutogeneratedFile(
	destinationPath: string, generator: (
		session: EnkoreSessionAPI,
		destinationPath: string
	) => Promise<string> | string
): EnkoreAutogeneratedFile {
	return createEntity("EnkoreAutogeneratedFile", 0, 0, {
		destinationPath,
		generator
	})
}
