import type {InternalSession} from "#~src/internal/InternalSession.d.mts"
import type {PreInit} from "../Steps.d.mts"
import {defineStep} from "../defineStep.mts"
import clean from "../1.clean/index.mts"
import {runHook} from "#~src/internal/session/runHook.mts"

async function executeStep(
	session: InternalSession
) : Promise<PreInit> {
	const {projectConfig} = session

	//
	// give realm a chance to register auto files
	//
	runHook(session, "preInitialize")

	//
	// add auto files from config to session
	//
	if (projectConfig.autogeneratedFiles) {
		for (const file of projectConfig.autogeneratedFiles) {
			session.publicAPI.addAutogeneratedFile(file)
		}
	}

	session.state.finalized = true

	return {
		clean: async function() {
			return await clean.runStep(session)
		}
	}
}

export default defineStep("preInit", executeStep)
