import type {PreInit} from "#~synthetic/user/Steps.d.mts"
import {defineStepChecked} from "../defineStepChecked.mts"
import clean from "../1.clean/index.mts"
import {runHook} from "#~src/internal/session/runHook.mts"
import {writeBoilerplateFiles} from "./writeBoilerplateFiles.mts"
import {writeGitIgnoreFile} from "./writeGitIgnoreFile.mts"

const executeStep: PreInit = async function(session) {
	const {projectConfig} = session

	await writeBoilerplateFiles(session)
	await writeGitIgnoreFile(session)

	//
	// give realm a chance to register auto files
	//
	await runHook(session, "preInitialize")

	//
	// add auto files from config to session
	//
	if (projectConfig.autogeneratedFiles) {
		for (const file of projectConfig.autogeneratedFiles) {
			session.publicAPI.addAutogeneratedFile(file)
		}
	}

	session.state.finalized = true

	return {
		clean: async function() {
			return await clean.runStep(session)
		}
	}
}

export default defineStepChecked("preInit", executeStep)
