import type {InternalSession} from "#~src/internal/InternalSession.ts"

export async function checkHashesOfAutogeneratedFiles(
	session: InternalSession
) {
	const lockFileData = session.coreInstance.initialLockFile

	const sz1 = session.state.filesToAutogenerate.size
	const sz2 = Object.keys(lockFileData.autogeneratedFiles).length

	if (sz1 !== sz2) {
		throw new Error(
			`Expected number of hashes to match number of autogenerated files:\n\n` +
			`Expected number: ${sz1}\n` +
			`Actual number  : ${sz2}\n`
		)
	}

	for (const path in lockFileData.autogeneratedFiles) {
		const expectedHash = lockFileData.autogeneratedFiles[path].hash

		if (!session.state.filesToAutogenerate.has(path)) {
			throw new Error(`No hash entry for autogenerated file '${path}'.`)
		}

		const actualHash = session.state.filesToAutogenerate.get(path)!.outputHash

		if (expectedHash !== actualHash) {
			throw new Error(
				`Hash of autogenerated file '${path}' does not match with what's inside of enkore-lock.json.\n` +
				`Expected hash: ${expectedHash}\n` +
				`Actual hash  : ${actualHash}\n`
			)
		}
	}
}
