import type {InternalSession} from "#~src/internal/InternalSession.ts"
import type {EnkoreLockFile} from "@anio-software/enkore-private.spec"

export async function updateHashesOfAutogeneratedFiles(
	session: InternalSession
): Promise<EnkoreLockFile> {
	const files = (() => {
		const ret: {
			[path: string]: {hash: string}
		} = {}

		for (const [key, value] of session.state.filesToAutogenerate.entries()) {
			ret[key] = {
				hash: value.outputHash!
			}
		}

		return ret
	})()

	return await session.coreInstance.updateLockfileAutogeneratedFiles(files)
}
