import type {InternalSession} from "#~src/internal/InternalSession.ts"

export async function updateHashesOfAutogeneratedFiles(
	session: InternalSession
) {
	const files = (() => {
		const ret: {
			[path: string]: {hash: string}
		} = {}

		for (const [key, value] of session.state.filesToAutogenerate.entries()) {
			ret[key] = {
				hash: value.outputHash!
			}
		}

		return ret
	})()

	await session.coreInstance.updateLockfileAutogeneratedFiles(files)
}
