import type {InternalSession} from "#~src/internal/InternalSession.d.mts"
import {writeAtomicFile} from "@anio-software/pkg.node-fs"
import path from "node:path"

export async function updateProjectSourceGitIgnoreFile(
	session: InternalSession
) {
	let gitIgnoreSource = ``

	gitIgnoreSource += `# This file is automatically managed by enkore\n`
	gitIgnoreSource += `# DO NOT ADD ENTRIES HERE, THEY WILL BE REMOVED\n`

	for (const [key] of session.state.filesToAutogenerate.entries()) {
		// all autogenerated destination paths must start with project/
		if (!key.startsWith("project/")) {
			throw new Error(`internal error, key doesn't start with 'project/'.`)
		}

		gitIgnoreSource += `/${key.slice("project/".length)}\n`
	}

	await writeAtomicFile(
		path.join(session.projectRoot, "project", ".gitignore"),
		gitIgnoreSource
	)
}
