import {
	type EnkoreBoilerplateFile,
	createEntity
} from "@asint/enkore__spec"
import {enkoreBoilerplateFileMarkerUUID} from "@asint/enkore__spec/uuid"

import {getAsset} from "@fourtune/realm-js/v0/assets"

export function getBoilerplateFiles() : EnkoreBoilerplateFile[] {
	const files : EnkoreBoilerplateFile[] = []

	function addFile(path: string, content: string, fullyManagedByEnkore?: boolean, executable?: boolean) {
		files.push(
			createEntity("EnkoreBoilerplateFile", 0, 0, {
				requestedBy: "enkore",
				path,
				content,
				fullyManagedByEnkore,
				fileIsExecutable: executable
			})
		)
	}

	const header = (() => {
		let tmp = ``

		tmp += `# DO NOT EDIT THIS FILE\n`
		tmp += `# ${enkoreBoilerplateFileMarkerUUID}\n`

		return tmp
	})()

	addFile(".editorconfig", header + getAsset("text://boilerplate/editorconfig") as string, true)

	addFile(".github/CODEOWNERS", header + getAsset("text://boilerplate/github/CODEOWNERS") as string, true)
	addFile(".github/workflows/cicd.yaml", header + getAsset("text://boilerplate/github/cicd_workflow.yaml") as string, true)
	addFile(".github/actions/setup/action.yaml", header + getAsset("text://boilerplate/github/cicd_setup_action.yaml") as string, true)

	addFile(".cicd/test.sh", `#!/bin/bash -euf\n\n./node_modules/.bin/enkore . -ci -test\n`, false, true)
	addFile(".cicd/deploy.sh", `#!/bin/bash -euf\n\n./node_modules/.bin/enkore . -ci -test -publish\n`, false, true)

	return files
}
