import type {
	EnkoreAutogeneratedFile,
	EnkoreProjectFile
} from "@enkore/spec"

import type {Step} from "#~src/internal/Step.d.mts"
import type {ScandirEntry} from "@aniojs/node-fs"

export type InternalSessionState = {
	// prevent addition of files
	// changes in config
	// after we initialized
	finalized: boolean

	currentStep: Step|undefined

	projectDirectoryEntries: ScandirEntry[]|undefined
	filteredProjectFiles: EnkoreProjectFile[]|undefined
	allProjectFiles: EnkoreProjectFile[]|undefined

	productNames: string[]

	filesToAutogenerate: Map<string, {
		normalizedDestinationPath: string
		generator: EnkoreAutogeneratedFile["generator"]
		output: string|undefined
		outputHash: string|undefined
	}>

	internalRealmData: object
}
