import type {
	EnkoreRealmIntegrationAPI,
	EnkoreAutoGeneratedFile,
	EnkoreSessionAPI,
	EnkoreConfig,
	RawType,
	EnkoreNodeAPIOptions
} from "@enkore/spec"

import type {Events} from "./Events.d.mts"
import type {_EmitEventType} from "@aniojs/event-emitter"
import type {ScandirEntry} from "@aniojs/node-fs"

export type InternalSession = {
	// prevent addition of files
	// changes in config
	// after we initialized
	finalized: boolean

	options: Required<RawType<EnkoreNodeAPIOptions>>

	projectRoot: string
	projectConfig: EnkoreConfig

	realmIntegrationAPI: EnkoreRealmIntegrationAPI

	projectDirectoryEntries?: ScandirEntry[]

	productNames: string[]

	filesToAutoGenerate: Map<string, {
		normalizedDestinationPath: string
		generator: EnkoreAutoGeneratedFile["generator"]
		output: string|undefined
		outputHash: string|undefined
	}>

	publicAPI: EnkoreSessionAPI

	emitEvent: _EmitEventType<Events>
}
