import type {
	EnkoreAutogeneratedFile
} from "@enkore/spec"

import type {ScandirEntry} from "@aniojs/node-fs"

export type InternalSessionState = {
	// prevent addition of files
	// changes in config
	// after we initialized
	finalized: boolean

	projectDirectoryEntries?: ScandirEntry[]

	productNames: string[]

	filesToAutogenerate: Map<string, {
		normalizedDestinationPath: string
		generator: EnkoreAutogeneratedFile["generator"]
		output: string|undefined
		outputHash: string|undefined
	}>
}
