import type {
	EnkoreRealmIntegrationAPI,
	EnkoreAutogeneratedFile,
	EnkoreSessionAPI,
	EnkoreConfig,
	RawType,
	EnkoreNodeAPIOptions
} from "@enkore/spec"

import type {Events} from "./Events.d.mts"
import type {Step} from "./Step.d.mts"
import type {_EmitEventType} from "@aniojs/event-emitter"
import type {ScandirEntry} from "@aniojs/node-fs"

import type {InternalSessionState} from "./InternalSessionState.d.mts"

export type InternalSession = {
	state: InternalSessionState

	getCurrentStep: () => Step|undefined
	setCurrentStep: (step: Step) => undefined

	debugPrint: (message: string) => undefined

	// prevent addition of files
	// changes in config
	// after we initialized
	finalized: boolean

	options: Required<RawType<EnkoreNodeAPIOptions>>

	projectRoot: string
	projectConfig: EnkoreConfig

	realmIntegrationAPI: EnkoreRealmIntegrationAPI

	projectDirectoryEntries?: ScandirEntry[]

	productNames: string[]

	filesToAutogenerate: Map<string, {
		normalizedDestinationPath: string
		generator: EnkoreAutogeneratedFile["generator"]
		output: string|undefined
		outputHash: string|undefined
	}>

	publicAPI: EnkoreSessionAPI

	emitEvent: _EmitEventType<Events>
}
