import type {ScandirEntry} from "@aniojs/node-fs"
import type {InternalSessionState} from "./InternalSessionState.d.mts"
import {createEntity} from "@asint/enkore__spec"

export function scandirEntryToEntityFactory(state: InternalSessionState) {
	return function(entry: ScandirEntry) {
		return createEntity("EnkoreProjectFile", 0, 0, {
			absolutePath: entry.absolute_path,
			relativePath: entry.relative_path,
			fileName: entry.name,
			wasAutogenerated: state.filesToAutogenerate.has(entry.relative_path),
			wasFiltered: false
		})
	}
}
