import {autogeneratedFileMarkerUUID} from "@anio-software/enkore-private.spec/uuid"
import {readFileInChunks} from "@anio-software/pkg.node-fs"

export async function isAutogeneratedFile(filePath: string) {
	const tmp = await readFileInChunks(filePath, 512)
	const chunk = await tmp.readNextChunk()

	await tmp.close()

	if (chunk === false) {
		return false
	}

	return chunk.toString().includes(autogeneratedFileMarkerUUID)
}
