import type {InternalSession} from "#~src/internal/InternalSession.d.mts"
import {createAutogeneratedFile} from "#~src/internal/autogenerate/createAutogeneratedFile.mts"

export async function createAutogeneratedFiles(
	session: InternalSession
) {
	for (const [_, file] of session.state.filesToAutogenerate.entries()) {
		const result = await createAutogeneratedFile(session, file)

		if (result === false) continue

		file.output = result.output
		file.outputHash = result.outputHash
	}
}
