import {
	type EnkoreBoilerplateFile,
	createEntity
} from "@anio-software/enkore-private.spec"
import {enkoreBoilerplateFileMarkerUUID} from "@anio-software/enkore-private.spec/uuid"

import {getEmbedAsString} from "@anio-software/enkore.target-js-node/project"

export function getBoilerplateFiles() : EnkoreBoilerplateFile[] {
	const files : EnkoreBoilerplateFile[] = []

	function addFile(path: string, content: string, fullyManagedByEnkore?: boolean, executable?: boolean) {
		files.push(
			createEntity("EnkoreBoilerplateFile", 0, 0, {
				requestedBy: "enkore",
				path,
				content,
				fullyManagedByEnkore,
				fileIsExecutable: executable
			})
		)
	}

	const header = (() => {
		let tmp = ``

		tmp += `# DO NOT EDIT THIS FILE\n`
		tmp += `# ${enkoreBoilerplateFileMarkerUUID}\n`

		return tmp
	})()

	addFile(".editorconfig", header + getEmbedAsString("text://boilerplate/editorconfig"), true)

	addFile(".github/CODEOWNERS", header + getEmbedAsString("text://boilerplate/github/CODEOWNERS"), true)
	addFile(".github/workflows/cicd.yaml", header + getEmbedAsString("text://boilerplate/github/cicd_workflow.yaml"), true)
	addFile(".github/actions/setup/action.yaml", header + getEmbedAsString("text://boilerplate/github/cicd_setup_action.yaml"), true)

	addFile(".cicd/test.sh", `#!/bin/bash -euf\n\n./node_modules/.bin/enkore . -ci -test\n`, false, true)
	addFile(".cicd/deploy.sh", `#!/bin/bash -euf\n\n./node_modules/.bin/enkore . -ci -test -publish\n`, false, true)

	return files
}
