import type {
	EnkoreAutogeneratedFile,
	EnkoreProjectFile,
	EnkoreBuildFile,
	EnkoreLockFile
} from "@anio-software/enkore-private.spec"

import type {Step} from "#~src/Steps.ts"
import type {ScandirEntry} from "@anio-software/pkg.node-fs"

export type FileToAutogenerate = {
	generateAfterPreprocessing: boolean
	normalizedDestinationPath: string
	generator: EnkoreAutogeneratedFile["generator"]
	output: string|undefined
	outputHash: string|undefined
}

export type InternalSessionState = {
	// prevent addition of files
	// changes in config
	// after we initialized
	finalized: boolean

	currentStep: Step|undefined

	filesTrackedByGit: Map<string, {}>

	buildFilesCreatedByPreprocessingStageByRelativePath: Map<string, ScandirEntry>
	projectFiles: Map<string, EnkoreProjectFile>
	buildFiles: Map<string, EnkoreBuildFile>

	productNames: string[]

	hasEncounteredError: boolean

	filesToAutogenerate: Map<string, FileToAutogenerate>

	// if this is null it means lock file data has not been synced yet.
	lockFileData: EnkoreLockFile|null

	// flag to emit warning when 'createdObjectFilesByRelativeSourceFilePath'
	// is accessed before compilation has finished.
	hasFinishedCompiling: boolean
	createdObjectFilesByRelativeSourceFilePath: Map<string, string[]>

	internalTargetData: object
}
